###----------------------------------User API----------------------------------#

### Sign up user

POST http://localhost:3000/api/v1/user/signup HTTP/1.1
Content-Type: application/json

{
    "username": "test_user",
    "password": "test_password"
}

### sign in user

POST http://localhost:3000/api/v1/user/signin HTTP/1.1
Content-Type: application/json

{
    "username": "test_user",
    "password": "test_password"
}

### Get user Details

GET http://localhost:3000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM

### patch user

PATCH  http://localhost:3000/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM
Content-Type: application/json

{
    "username": "test_user",
    "password": "test_password"
}

### delete user
DELETE http://localhost:3000/api/v1/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM


###-------------------------Timetable API---------------------------#

### Post new timetable

POST http://localhost:3000/api/v1/user/timetables HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM
Content-Type: application/json

{
    "description": "test_timetable"
}

### get All timetable

GET http://localhost:3000/api/v1/user/timetables HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM

### get timetable by id

GET http://localhost:3000/api/v1/user/timetables/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM

### patch timetable

PATCH http://localhost:3000/api/v1/user/timetables/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM
Content-Type: application/json

{
    "description": "test_timetable"
}

### delete timetable
DELETE http://localhost:3000/api/v1/user/timetables/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM

###-------------------------Schedule API---------------------------#

### POST new schedule

POST http://localhost:3000/api/v1/user/timetables/2/schedules HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM
Content-Type: application/json

{
    "description": "test_schedule",
    "start": "2020-01-01T00:00:00.000Z",
    "end": "2020-01-01T00:00:00.000Z",
    "finished": false
}

### get All schedule

GET http://localhost:3000/api/v1/user/timetables/2/schedules HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM

### get schedule by id

GET http://localhost:3000/api/v1/user/timetables/2/schedules/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM

### patch schedule

PATCH http://localhost:3000/api/v1/user/timetables/2/schedules/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM
Content-Type: application/json

{
    "description": "test_schedule",
    "start": "2020-01-01T00:00:00.000Z",
    "end": "2020-01-01T00:00:00.000Z",
    "finished": false
}

### delete schedule

DELETE http://localhost:3000/api/v1/user/timetables/2/schedules/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJpYXQiOjE2NTM5OTM0MzR9.FUcbrhLT3iXs62L4Ljt2a3Y5frbvGD2lN-loI2-QynM
